/**
 * Trainer sprites for Trainer ID profile avatar.
 * Sprites from Pokémon Showdown (play.pokemonshowdown.com/sprites/trainers/).
 * Only IDs that exist in the official smogon/sprites repo (ps-trainers.sheet.mjs) are included.
 */

const BASE = 'https://play.pokemonshowdown.com/sprites/trainers';

export function getTrainerSpriteUrl(id: string): string {
  return `${BASE}/${id}.png`;
}

/** Default trainer sprite (Red). Used when user has not selected a trainer. */
export const DEFAULT_TRAINER_ID = 'red';
export const DEFAULT_TRAINER_SPRITE_URL = getTrainerSpriteUrl(DEFAULT_TRAINER_ID);

/** Human-readable name for a trainer id. */
function displayName(id: string): string {
  const names: Record<string, string> = {
    lucas: 'Lucas',
    dawn: 'Dawn',
    'youngster-gen4': 'Youngster (Gen 4)',
    'lass-gen4dp': 'Lass (Gen 4)',
    camper: 'Camper',
    picnicker: 'Picnicker',
    bugcatcher: 'Bug Catcher',
    aromalady: 'Aroma Lady',
    'twins-gen4dp': 'Twins (Gen 4)',
    'hiker-gen4': 'Hiker (Gen 4)',
    'battlegirl-gen4': 'Battle Girl (Gen 4)',
    'fisherman-gen4': 'Fisherman (Gen 4)',
    'cyclist-gen4': 'Cyclist (Gen 4)',
    'cyclistf-gen4': 'Cyclist (F) (Gen 4)',
    'blackbelt-gen4dp': 'Black Belt (Gen 4)',
    'artist-gen4': 'Artist (Gen 4)',
    'pokemonbreeder-gen4': 'Pokémon Breeder (Gen 4)',
    'pokemonbreederf-gen4': 'Pokémon Breeder (F) (Gen 4)',
    cowgirl: 'Cowgirl',
    jogger: 'Jogger',
    'pokefan-gen4': 'Pokéfan (Gen 4)',
    'pokefanf-gen4': 'Pokéfan (F) (Gen 4)',
    pokekid: 'Poké Kid',
    'youngcouple-gen4dp': 'Young Couple (Gen 4)',
    'acetrainer-gen4dp': 'Ace Trainer (Gen 4)',
    'acetrainerf-gen4dp': 'Ace Trainer (F) (Gen 4)',
    'waitress-gen4': 'Waitress (Gen 4)',
    'veteran-gen4': 'Veteran (Gen 4)',
    ninjaboy: 'Ninja Boy',
    dragontamer: 'Dragon Tamer',
    'birdkeeper-gen4dp': 'Bird Keeper (Gen 4)',
    doubleteam: 'Double Team',
    'richboy-gen4': 'Rich Boy (Gen 4)',
    'lady-gen4': 'Lady (Gen 4)',
    'gentleman-gen4dp': 'Gentleman (Gen 4)',
    'madame-gen4dp': 'Madame (Gen 4)',
    'beauty-gen4dp': 'Beauty (Gen 4)',
    collector: 'Collector',
    'policeman-gen4': 'Policeman (Gen 4)',
    'pokemonranger-gen4': 'Pokémon Ranger (Gen 4)',
    'pokemonrangerf-gen4': 'Pokémon Ranger (F) (Gen 4)',
    'scientist-gen4dp': 'Scientist (Gen 4)',
    'swimmer-gen4dp': 'Swimmer (Gen 4)',
    'swimmerf-gen4dp': 'Swimmer (F) (Gen 4)',
    tuber: 'Tuber',
    tuberf: 'Tuber (F)',
    sailor: 'Sailor',
    sisandbro: 'Sis and Bro',
    ruinmaniac: 'Ruin Maniac',
    'psychic-gen4': 'Psychic (Gen 4)',
    'psychicf-gen4': 'Psychic (F) (Gen 4)',
    gambler: 'Gambler',
    'guitarist-gen4': 'Guitarist (Gen 4)',
    acetrainersnow: 'Ace Trainer (Snow)',
    acetrainersnowf: 'Ace Trainer (Snow, F)',
    skier: 'Skier',
    'skierf-gen4dp': 'Skier (F) (Gen 4)',
    'roughneck-gen4': 'Roughneck (Gen 4)',
    clown: 'Clown',
    'worker-gen4': 'Worker (Gen 4)',
    'schoolkid-gen4dp': 'School Kid (Gen 4)',
    'schoolkidf-gen4': 'School Kid (F) (Gen 4)',
    roark: 'Roark',
    barry: 'Barry',
    byron: 'Byron',
    aaron: 'Aaron',
    bertha: 'Bertha',
    flint: 'Flint',
    lucian: 'Lucian',
    'cynthia-gen4': 'Cynthia (Gen 4)',
    bellepa: 'Belle & Pa',
    rancher: 'Rancher',
    mars: 'Mars',
    galacticgrunt: 'Galactic Grunt',
    gardenia: 'Gardenia',
    crasherwake: 'Crasher Wake',
    maylene: 'Maylene',
    fantina: 'Fantina',
    candice: 'Candice',
    volkner: 'Volkner',
    'parasollady-gen4': 'Parasol Lady (Gen 4)',
    'waiter-gen4dp': 'Waiter (Gen 4)',
    interviewers: 'Interviewers',
    cameraman: 'Cameraman',
    reporter: 'Reporter',
    idol: 'Idol',
    cyrus: 'Cyrus',
    jupiter: 'Jupiter',
    saturn: 'Saturn',
    galacticgruntf: 'Galactic Grunt (F)',
    argenta: 'Argenta',
    palmer: 'Palmer',
    thorton: 'Thorton',
    buck: 'Buck',
    darach: 'Darach',
    marley: 'Marley',
    mira: 'Mira',
    cheryl: 'Cheryl',
    riley: 'Riley',
    dahlia: 'Dahlia',
    ethan: 'Ethan',
    lyra: 'Lyra',
    'twins-gen4': 'Twins (Gen 4)',
    'lass-gen4': 'Lass (Gen 4)',
    'acetrainer-gen4': 'Ace Trainer (Gen 4)',
    'acetrainerf-gen4': 'Ace Trainer (F) (Gen 4)',
    juggler: 'Juggler',
    sage: 'Sage',
    li: 'Li',
    'gentleman-gen4': 'Gentleman (Gen 4)',
    teacher: 'Teacher',
    beauty: 'Beauty',
    birdkeeper: 'Bird Keeper',
    'swimmer-gen4': 'Swimmer (Gen 4)',
    'swimmerf-gen4': 'Swimmer (F) (Gen 4)',
    kimonogirl: 'Kimono Girl',
    'scientist-gen4': 'Scientist (Gen 4)',
    acetrainercouple: 'Ace Trainer Couple',
    youngcouple: 'Young Couple',
    supernerd: 'Super Nerd',
    medium: 'Medium',
    'schoolkid-gen4': 'School Kid (Gen 4)',
    'blackbelt-gen4': 'Black Belt (Gen 4)',
    pokemaniac: 'Pokémaniac',
    firebreather: 'Firebreather',
    burglar: 'Burglar',
    'biker-gen4': 'Biker (Gen 4)',
    skierf: 'Skier (F)',
    boarder: 'Boarder',
    rocketgrunt: 'Rocket Grunt',
    rocketgruntf: 'Rocket Grunt (F)',
    archer: 'Archer',
    ariana: 'Ariana',
    proton: 'Proton',
    petrel: 'Petrel',
    eusine: 'Eusine',
    'lucas-gen4pt': 'Lucas (Platinum)',
    'dawn-gen4pt': 'Dawn (Platinum)',
    'madame-gen4': 'Madame (Gen 4)',
    'waiter-gen4': 'Waiter (Gen 4)',
    falkner: 'Falkner',
    bugsy: 'Bugsy',
    whitney: 'Whitney',
    morty: 'Morty',
    chuck: 'Chuck',
    jasmine: 'Jasmine',
    pryce: 'Pryce',
    clair: 'Clair',
    will: 'Will',
    koga: 'Koga',
    bruno: 'Bruno',
    karen: 'Karen',
    lance: 'Lance',
    brock: 'Brock',
    misty: 'Misty',
    ltsurge: 'Lt. Surge',
    erika: 'Erika',
    janine: 'Janine',
    sabrina: 'Sabrina',
    blaine: 'Blaine',
    blue: 'Blue',
    red: 'Red',
    silver: 'Silver',
    giovanni: 'Giovanni',
    hilbert: 'Hilbert',
    hilda: 'Hilda',
    youngster: 'Youngster',
    lass: 'Lass',
    schoolkid: 'School Kid',
    schoolkidf: 'School Kid (F)',
    smasher: 'Smasher',
    linebacker: 'Linebacker',
    waiter: 'Waiter',
    waitress: 'Waitress',
    chili: 'Chili',
    cilan: 'Cilan',
    cress: 'Cress',
    nurseryaide: 'Nursery Aide',
    preschoolerf: 'Preschooler (F)',
    preschooler: 'Preschooler',
    twins: 'Twins',
    pokemonbreeder: 'Pokémon Breeder',
    pokemonbreederf: 'Pokémon Breeder (F)',
    lenora: 'Lenora',
    burgh: 'Burgh',
    elesa: 'Elesa',
    clay: 'Clay',
    skyla: 'Skyla',
    pokemonranger: 'Pokémon Ranger',
    pokemonrangerf: 'Pokémon Ranger (F)',
    worker: 'Worker',
    backpacker: 'Backpacker',
    backpackerf: 'Backpacker (F)',
    fisherman: 'Fisherman',
    musician: 'Musician',
    dancer: 'Dancer',
    harlequin: 'Harlequin',
    artist: 'Artist',
    baker: 'Baker',
    psychic: 'Psychic',
    psychicf: 'Psychic (F)',
    cheren: 'Cheren',
    bianca: 'Bianca',
    'plasmagrunt-gen5bw': 'Plasma Grunt (Gen 5)',
    n: 'N',
    richboy: 'Rich Boy',
    lady: 'Lady',
    pilot: 'Pilot',
    workerice: 'Worker (Ice)',
    hoopster: 'Hoopster',
    scientistf: 'Scientist (F)',
    clerkf: 'Clerk (F)',
    acetrainerf: 'Ace Trainer (F)',
    acetrainer: 'Ace Trainer',
    blackbelt: 'Black Belt',
    scientist: 'Scientist',
    striker: 'Striker',
    brycen: 'Brycen',
    iris: 'Iris',
    drayden: 'Drayden',
    roughneck: 'Roughneck',
    janitor: 'Janitor',
    pokefan: 'Pokéfan',
    pokefanf: 'Pokéfan (F)',
    doctor: 'Doctor',
    nurse: 'Nurse',
    hooligans: 'Hooligans',
    battlegirl: 'Battle Girl',
    parasollady: 'Parasol Lady',
    clerk: 'Clerk',
    'clerk-boss': 'Clerk (Boss)',
    backers: 'Backers',
    backersf: 'Backers (F)',
    veteran: 'Veteran',
    veteranf: 'Veteran (F)',
    biker: 'Biker',
    infielder: 'Infielder',
    hiker: 'Hiker',
    madame: 'Madame',
    gentleman: 'Gentleman',
    'plasmagruntf-gen5bw': 'Plasma Grunt (F) (Gen 5)',
    shauntal: 'Shauntal',
    marshal: 'Marshal',
    grimsley: 'Grimsley',
    caitlin: 'Caitlin',
    'ghetsis-gen5bw': 'Ghetsis (Gen 5)',
    depotagent: 'Depot Agent',
    swimmer: 'Swimmer',
    swimmerf: 'Swimmer (F)',
    policeman: 'Policeman',
    maid: 'Maid',
    ingo: 'Ingo',
    alder: 'Alder',
    cyclist: 'Cyclist',
    cyclistf: 'Cyclist (F)',
    cynthia: 'Cynthia',
    emmet: 'Emmet',
    'hilbert-dueldisk': 'Hilbert (Duel Disk)',
    'hilda-dueldisk': 'Hilda (Duel Disk)',
    hugh: 'Hugh',
    rosa: 'Rosa',
    nate: 'Nate',
    colress: 'Colress',
    'beauty-gen5bw2': 'Beauty (Gen 5 B2W2)',
    ghetsis: 'Ghetsis',
    plasmagrunt: 'Plasma Grunt',
    plasmagruntf: 'Plasma Grunt (F)',
    'iris-gen5bw2': 'Iris (Gen 5 B2W2)',
    brycenman: 'Brycen-Man',
    shadowtriad: 'Shadow Triad',
    rood: 'Rood',
    zinzolin: 'Zinzolin',
    'cheren-gen5bw2': 'Cheren (Gen 5 B2W2)',
    marlon: 'Marlon',
    roxie: 'Roxie',
    roxanne: 'Roxanne',
    brawly: 'Brawly',
    wattson: 'Wattson',
    flannery: 'Flannery',
    norman: 'Norman',
    winona: 'Winona',
    tate: 'Tate',
    liza: 'Liza',
    juan: 'Juan',
    guitarist: 'Guitarist',
    steven: 'Steven',
    wallace: 'Wallace',
    bellelba: 'Bellelba',
    benga: 'Benga',
  };
  if (names[id]) return names[id];
  return id.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
}

/** Unique trainer IDs from the official sprite sheet (smogon/sprites ps-trainers.sheet.mjs). */
const SHEET_IDS = [
  'lucas', 'dawn', 'youngster-gen4', 'lass-gen4dp', 'camper', 'picnicker', 'bugcatcher', 'aromalady',
  'twins-gen4dp', 'hiker-gen4', 'battlegirl-gen4', 'fisherman-gen4', 'cyclist-gen4', 'cyclistf-gen4',
  'blackbelt-gen4dp', 'artist-gen4', 'pokemonbreeder-gen4', 'pokemonbreederf-gen4', 'cowgirl', 'jogger',
  'pokefan-gen4', 'pokefanf-gen4', 'pokekid', 'youngcouple-gen4dp', 'acetrainer-gen4dp', 'acetrainerf-gen4dp',
  'waitress-gen4', 'veteran-gen4', 'ninjaboy', 'dragontamer', 'birdkeeper-gen4dp', 'doubleteam',
  'richboy-gen4', 'lady-gen4', 'gentleman-gen4dp', 'madame-gen4dp', 'beauty-gen4dp', 'collector',
  'policeman-gen4', 'pokemonranger-gen4', 'pokemonrangerf-gen4', 'scientist-gen4dp', 'swimmer-gen4dp', 'swimmerf-gen4dp',
  'tuber', 'tuberf', 'sailor', 'sisandbro', 'ruinmaniac', 'psychic-gen4', 'psychicf-gen4', 'gambler',
  'guitarist-gen4', 'acetrainersnow', 'acetrainersnowf', 'skier', 'skierf-gen4dp', 'roughneck-gen4', 'clown',
  'worker-gen4', 'schoolkid-gen4dp', 'schoolkidf-gen4', 'roark', 'barry', 'byron', 'aaron', 'bertha',
  'flint', 'lucian', 'cynthia-gen4', 'bellepa', 'rancher', 'mars', 'galacticgrunt', 'gardenia',
  'crasherwake', 'maylene', 'fantina', 'candice', 'volkner', 'parasollady-gen4', 'waiter-gen4dp',
  'interviewers', 'cameraman', 'reporter', 'idol', 'cyrus', 'jupiter', 'saturn', 'galacticgruntf',
  'argenta', 'palmer', 'thorton', 'buck', 'darach', 'marley', 'mira', 'cheryl', 'riley', 'dahlia',
  'ethan', 'lyra', 'twins-gen4', 'lass-gen4', 'acetrainer-gen4', 'acetrainerf-gen4', 'juggler', 'sage', 'li',
  'gentleman-gen4', 'teacher', 'beauty', 'birdkeeper', 'swimmer-gen4', 'swimmerf-gen4', 'kimonogirl',
  'scientist-gen4', 'acetrainercouple', 'youngcouple', 'supernerd', 'medium', 'schoolkid-gen4', 'blackbelt-gen4',
  'pokemaniac', 'firebreather', 'burglar', 'biker-gen4', 'skierf', 'boarder', 'rocketgrunt', 'rocketgruntf',
  'archer', 'ariana', 'proton', 'petrel', 'eusine', 'lucas-gen4pt', 'dawn-gen4pt', 'madame-gen4', 'waiter-gen4',
  'falkner', 'bugsy', 'whitney', 'morty', 'chuck', 'jasmine', 'pryce', 'clair', 'will', 'koga', 'bruno', 'karen',
  'lance', 'brock', 'misty', 'ltsurge', 'erika', 'janine', 'sabrina', 'blaine', 'blue', 'red', 'silver', 'giovanni',
  'hilbert', 'hilda', 'youngster', 'lass', 'schoolkid', 'schoolkidf', 'smasher', 'linebacker', 'waiter', 'waitress',
  'chili', 'cilan', 'cress', 'nurseryaide', 'preschoolerf', 'preschooler', 'twins', 'pokemonbreeder', 'pokemonbreederf',
  'lenora', 'burgh', 'elesa', 'clay', 'skyla', 'pokemonranger', 'pokemonrangerf', 'worker', 'backpacker', 'backpackerf',
  'fisherman', 'musician', 'dancer', 'harlequin', 'artist', 'baker', 'psychic', 'psychicf', 'cheren', 'bianca',
  'plasmagrunt-gen5bw', 'n', 'richboy', 'lady', 'pilot', 'workerice', 'hoopster', 'scientistf', 'clerkf',
  'acetrainerf', 'acetrainer', 'blackbelt', 'scientist', 'striker', 'brycen', 'iris', 'drayden', 'roughneck', 'janitor',
  'pokefan', 'pokefanf', 'doctor', 'nurse', 'hooligans', 'battlegirl', 'parasollady', 'clerk', 'clerk-boss',
  'backers', 'backersf', 'veteran', 'veteranf', 'biker', 'infielder', 'hiker', 'madame', 'gentleman',
  'plasmagruntf-gen5bw', 'shauntal', 'marshal', 'grimsley', 'caitlin', 'ghetsis-gen5bw', 'depotagent',
  'swimmer', 'swimmerf', 'policeman', 'maid', 'ingo', 'alder', 'cyclist', 'cyclistf', 'cynthia', 'emmet',
  'hilbert-dueldisk', 'hilda-dueldisk', 'hugh', 'rosa', 'nate', 'colress', 'beauty-gen5bw2', 'ghetsis',
  'plasmagrunt', 'plasmagruntf', 'iris-gen5bw2', 'brycenman', 'shadowtriad', 'rood', 'zinzolin', 'cheren-gen5bw2',
  'marlon', 'roxie', 'roxanne', 'brawly', 'wattson', 'flannery', 'norman', 'winona', 'tate', 'liza', 'juan',
  'guitarist', 'steven', 'wallace', 'bellelba', 'benga',
];

/** Trainer sprite id + display name for the picker. Only sprites that exist in the official sheet. */
export const TRAINER_SPRITES: { id: string; name: string }[] = SHEET_IDS.map((id) => ({
  id,
  name: displayName(id),
}));

const VALID_IDS = new Set(SHEET_IDS);

/** Whether this sprite id exists in the official sheet (use to fallback to default for old/invalid ids). */
export function isValidTrainerSpriteId(id: string): boolean {
  return VALID_IDS.has(id);
}
